{{- if .Values.initiator.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-initiator
  labels:
    app.kubernetes.io/name: vertx-initiator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vertx-initiator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vertx-initiator
        monitoring: appd-23_10_0
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.20.1"
    spec:
      containers:
        - name: initiator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-init"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
{{- end }}